import Loader from "@/components/common/loader";
import RootProvider from "@/providers/root-provider";
import "lenis/dist/lenis.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tanmay Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <RootProvider>
          <Suspense
            fallback={
              <div className="w-full h-screen flex items-center justify-center bg-white">
                <Loader />
              </div>
            }
          >
            {children}
          </Suspense>
        </RootProvider>
      </body>
    </html>
  );
}
